version: "3.7"
services:
  spark-master:
    image: bedman3/spark-master:latest
    ports:
      - "9090:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
       - /mnt:/mnt
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker:
    image: bedman3/spark-worker:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=3G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
